### ISSUE TITLE
No Control Button

### ISSUE THREAD

**Issue by albert-aja** [dvx/lofi#162] opened 2021-10-20 14:33 UTC
Everything works fine except my lofi is missing the control button such as play button, next button, etc. Does this feature require premium spotify account?

![Imgur](https://i.imgur.com/vFsRdrh.png)

**Comment by chiconws** [comment] 2021-11-18 12:45
About fowards and backwards:

FAQ: http://www.lofi.rocks/help
_I can't skip fowards or backwards.
Lofi is bound by Spotify's API contract. Much like in the real app, if you're using Lofi with a free Spotify account, track skipping or ad skipping won't work._

But it should have at least the play/pause button, right?

**Comment by stamoun** [comment] 2022-02-26 02:27
Nope, sadly, all playback through the API is disabled for non premium users :(

https://developer.spotify.com/documentation/web-playback-sdk/

Duplicate of #168

**Closed** 2022-02-26 02:27 UTC
Labels: duplicate, invalid
