### ISSUE TITLE
Cannot MOVE the lofi tile to the bottom right (preferred location)

### ISSUE THREAD

**Issue by lewis4help** [dvx/lofi#204] opened 2022-06-16 13:30 UTC
Hi there -
I am having issue trying to move my lofi tile to the bottom right of my display. It currently sits in the middle of my screen. Please help

![image](https://user-images.githubusercontent.com/107628915/174080852-0f9d3fe7-3b85-4382-918f-15da743ce7dc.png)

**Comment by stamoun** [comment] 2022-06-16 14:58
Yeah, no idea what's causing this, so you don't get anything when you hover over Lofi?

Possible duplicate of #194

**Comment by lewis4help** [comment] 2022-06-16 20:49
No. When I get to the settings area (top left), it disappears from me. Does
not allow me to move it

**Comment by stamoun** [comment] 2022-06-16 21:07
You can drag the application from anywhere in the UI, not just from the top.

**Comment by stamoun** [comment] 2023-09-30 15:02
Most likely fixed in 2.0.1

**Closed by stamoun** 2023-09-30 15:02 UTC
