### ISSUE TITLE
Controls don't work

### ISSUE THREAD

**Issue by evaniem** [dvx/lofi#78] opened 2020-08-20 11:21 UTC
None of the controls work. Play/pause, forward, back, nothing. The buttons in the corners work fine.
I installed the app just now, I tried restarting both it and Spotify a few times, running both in admin mode, restarting my PC, nothing works. 

In debug mode, it displays an error with event listeners.
![2020-08-20 13_08_08-Developer Tools - about_blank](https://user-images.githubusercontent.com/44981057/90763043-4ec35100-e2e6-11ea-9b84-302750b45454.png)

Now, I *am* currently using a free account and your FAQ does say skipping won't work, which is okay, but for me pausing/playing doesn't work either.

**Comment by burritosoftware** [comment] 2020-08-26 04:17
Controls still are not working after running Lofi as Admin and I can reproduce this issue on Windows 10 Home x64.

**Comment by Briahas** [comment] 2020-09-16 19:53
Same here - none control works. Same as Admin.

**Comment by stamoun** [comment] 2020-09-23 12:45
Cannot use playback controls via the API with a free account (c.f. [Spotify's docs](https://developer.spotify.com/documentation/web-api/reference/player/pause-a-users-playback/)).

> if the user making the request is non-premium, a 403 FORBIDDEN response code will be returned

That being said, I'm working on hiding the playback controls when the logged in account is not premium

**Comment by stamoun** [comment] 2020-10-06 18:48
IMO we can close this issue @dvx Version `1.5.3` removes playback buttons when the sub is not premium, this was merged in  #82

**Comment by burritosoftware** [comment] 2020-10-06 18:52
> IMO we can close this issue @dvx Version `1.5.3` removes playback buttons when the sub is not premium, this was merged in  #82 
> 
> 

I was talking in the lofi Discord about a workaround where the lofi app presses the media keys in the app, so that could be possible

**Comment by stamoun** [comment] 2020-10-06 19:53
I saw that message on Discord @burritosoftware and I agree with David; it seems this would be against the [ToS](https://developer.spotify.com/terms/).

Section IV.3.e.iii
> control of a background Spotify Application via the Spotify Platform, may be made available to Spotify users who do not subscribe to the Premium service to the extent such functionality is available through the Spotify Platform.

It's weirdly worded since a free account can actually control playback via the Spotify Application, but not via the API (Spotify Platform). I believe that it's a Spotify API issue, not a Lofi issue.

**Closed** 2020-11-09 18:10 UTC
