### ISSUE TITLE
Media controls for Spotify free

### ISSUE THREAD

**Issue by icruz95** [dvx/lofi#208] opened 2022-07-19 15:24 UTC
Even though Spotify's API does not allow media controls for free accounts, lofi could display the buttons and use the OS's media controls instead. 

So as a Spotify free user I could use the media controls in the lofi widget and have them work exactly like media shortcuts on my keyboard. 
It could be confusing with other media players/browsers using the controls when spotify isn't playing, but I would prefer this as a setting (disabled by default to prevent confusion) than the current solution.

**Comment by stamoun** [comment] 2022-07-19 15:28
That workaround is most likely against the Spotify API's ToS.

Duplicate of #78

**Closed by stamoun** 2022-07-19 15:28 UTC
