### ISSUE TITLE
not working on Macbook (Mojave)

### ISSUE THREAD

**Issue by cgm707** [dvx/lofi#1] opened 2019-02-15 01:22 UTC
I just downloaded and opened it on my Macbook Air (Mojave OS). Received the message about Java. 
![screen shot 2019-02-14 at 5 12 47 pm](https://user-images.githubusercontent.com/3260210/52828305-29181480-307d-11e9-8980-c03b5a63136d.jpg)

**Comment by dvx** [comment] 2019-02-15 02:00
Thanks for the issue! I'll take a look and see if I can reproduce this. On first thought, make sure the user you're running/installing Lofi as has Administrator access.

**Comment by polltery** [comment] 2019-02-15 12:33
Works fine on macOS Mojave (10.14)

**Comment by dvx** [comment] 2019-02-15 18:19
I couldn't reproduce this either (also on Mojave). Seems to be a permissions issue -- are you sure you're running the application as root?

**Comment by mikeymurph77** [comment] 2019-02-15 18:48
Same issue. I know I do not have admin access.

**Comment by dvx** [comment] 2019-02-15 19:45
Almost certain the issue is caused by this `chmodSync` [here](https://github.com/dvx/lofi/blob/1442996773041cc42114504d28db3df9e3c86678/src/main/main.ts#L18). I'll look into better ways of chmoding the MacOS volume daemon. It works fine on my MacBook Pro, but since a few people seem to have issues, it doesn't seem like `chmodSync` is a general solution.

**Comment by ckcollab** [comment] 2019-02-25 08:17
I got this on Sierra:

![image](https://user-images.githubusercontent.com/2185159/53323305-ab30e600-3892-11e9-80e8-5e3fda3c7060.png)

**Comment by dvx** [comment] 2020-07-08 20:43
Fixed with 1.5.0. No longer using volume daemon.

**Closed by dvx** 2020-07-08 20:43 UTC
Labels: bug, question

**Comment by ckcollab** [comment] 2020-07-08 21:11
Thanks!!
