### ISSUE TITLE
Cant click settings

### ISSUE THREAD

**Issue by jedi5579** [dvx/lofi#213] opened 2022-08-07 12:31 UTC
When I hover over the app it will show settings, the screen things, and all those things. But, when I move the mouse up a little, it seems that the app doesn't detect my cursor or something, so it fades away, and I am unable to click settings. It stops around 3/4 of the way up.

**Comment by stamoun** [comment] 2022-08-08 11:38
Duplicate of #194

**Closed** 2022-08-08 14:51 UTC
Labels: bug
