### ISSUE TITLE
Play/pause and next/back buttons don't work

### ISSUE THREAD

**Issue by KomiKatto** [dvx/lofi#93] opened 2020-11-01 23:50 UTC
- Play, pause and skip buttons don't work, but only work in the desktop app (which I installed from the Microsoft store).
- Pressing pause does not pause the music and just continues playing; there is a change in the pause/play icon when pressed, though. 
- Pressing skip/back does not change the track (No premium plan on my account, if that helps to know)

**Comment by stamoun** [comment] 2020-11-09 13:56
Duplicate of #78 

Can't use playback on freemium accounts

**Closed** 2020-11-09 18:10 UTC
